MODEL:
  TYPE: charw2cpos
  DEPTH: 1
  NUM_CLASSES: 2
  VOCAB_SIZE: 4941
  TAGS_SIZE: 204
  CWS_SIZE: 5
  POS_SIZE: 29
  FLAG_SIZE: 1
  EMBEDDING_DIM: 64
  NUM_LAYER: 1
  HIDDEN_DIM: 128
  PRETRAINED_EMBEDDING_DIM: 200
  DROPOUT_EMBEDDING: 0.3
  DROPOUT_BLSTM: 0.3
  DROPOUT_LINEAR: 0.3
  DROPOUT_INTER_BLSTM: 0.0

DEVICE: 'cuda:0'
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.001
  LR_POLICY: steps
  STEPS: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
  LR_MULT: 0.70
  MAX_EPOCH: 24
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00001
TRAIN:
  DATASET: 'charw2vposcwsflag'
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
TEST:
  DATASET: 'charw2vposcwsflag'
  SPLIT: test
  BATCH_SIZE: 256
  IM_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 16
CUDNN:
  BENCHMARK: True
OUT_DIR: 'save/outputs_charw2cpos_128dim_blstm'
