ANYNET:
  BLOCK_TYPE: res_bottleneck_block
  BOT_MULS: []
  DEPTHS: []
  GROUP_WS: []
  HEAD_W: 0
  SE_ON: false
  SE_R: 0.25
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STRIDES: []
  WIDTHS: []
BN:
  CUSTOM_WEIGHT_DECAY: 0.0
  EPS: 1.0e-05
  MOM: 0.1
  NUM_SAMPLES_PRECISE: 8192
  USE_CUSTOM_WEIGHT_DECAY: false
  USE_PRECISE_STATS: true
  ZERO_INIT_FINAL_GAMMA: true
CFG_DEST: config.yaml
CUDNN:
  BENCHMARK: true
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: true
DESC: ''
DIST_BACKEND: nccl
DOWNLOAD_CACHE: /tmp/pycls-download-cache
EN:
  DC_RATIO: 0.0
  DEPTHS: []
  DROPOUT_RATIO: 0.0
  EXP_RATIOS: []
  HEAD_W: 1280
  KERNELS: []
  SE_R: 0.25
  STEM_W: 32
  STRIDES: []
  WIDTHS: []
HOST: localhost
LOG_DEST: stdout
LOG_PERIOD: 10
MODEL:
  ACTIVATION_FUN: relu
  ACTIVATION_INPLACE: true
  DEPTH: 1
  LOSS_FUN: mse_loss
  NUM_CLASSES: 2
  SCALING_FACTOR: 1.0
  SCALING_TYPE: ''
  TYPE: charw2c
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.01
  DAMPENING: 0.0
  EMA_ALPHA: 1.0e-05
  EMA_UPDATE_PERIOD: 32
  LR_MULT: 0.1
  LR_POLICY: steps
  MAX_EPOCH: 100
  MIN_LR: 0.0
  MOMENTUM: 0.9
  NESTEROV: true
  STEPS:
  - 0
  - 30
  - 60
  - 90
  WARMUP_EPOCHS: 0
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 5.0e-05
OUT_DIR: .
PORT_RANGE:
- 10000
- 65000
PREC_TIME:
  NUM_ITER: 30
  WARMUP_ITER: 3
REGNET:
  BLOCK_TYPE: res_bottleneck_block
  BOT_MUL: 1.0
  DEPTH: 10
  GROUP_W: 16
  HEAD_W: 0
  SE_ON: false
  SE_R: 0.25
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STRIDE: 2
  W0: 32
  WA: 5.0
  WM: 2.5
RESNET:
  NUM_GROUPS: 1
  STRIDE_1X1: true
  TRANS_FUN: basic_transform
  WIDTH_PER_GROUP: 64
RNG_SEED: 1
TEST:
  BATCH_SIZE: 25
  DATASET: charw2vposcwsflag
  IM_SIZE: 256
  SPLIT: test
  WEIGHTS: ''
TRAIN:
  AUGMENT: ''
  AUTO_RESUME: true
  BATCH_SIZE: 128
  DATASET: charw2vposcwsflag
  IM_SIZE: 224
  LABEL_SMOOTHING: 0.0
  MIXED_PRECISION: false
  MIXUP_ALPHA: 0.0
  PCA_STD: 0.1
  SPLIT: train
  WEIGHTS: ''
VERBOSE: true
