MODEL:
  TYPE: beatnet
  DEPTH: 1
  NUM_CLASSES: 2
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.01
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00005
TRAIN:
  DATASET: gtzan
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
TEST:
  DATASET: gtzan
  SPLIT: val
  BATCH_SIZE: 25
  IM_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
